sudo: false
language: node_js
node_js:
- '0.12'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm prune
- npm install -g grunt-cli bower
- npm install && bower install
script:
- npm test
after_success:
- npm run semantic-release
cache:
  directories:
  - node_modules
notifications:
  email: false
