sudo: false
language: node_js
node_js:
- '0.12'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm prune
cache:
  directories:
  - node_modules
notifications:
  email: false
after_success:
  - npm run semantic-release
branches:
  except:
    # Ignore Git tags created by semantic-release, like "v1.2.3"
    - /^v\d+\.\d+\.\d+$/
